apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: client-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: do-block-storage
---
apiVersion: v1
kind: Service
metadata:
  name: client-mongo
spec:
  selector:
    app: client-mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-mongo
spec:
  selector:
    matchLabels:
      app: client-mongo
  template:
    metadata:
      labels:
        app: client-mongo
    spec:
      containers:
        - name: client-mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: client-storage
              mountPath: /data/db
      volumes:
        - name: client-storage
          persistentVolumeClaim:
            claimName: client-mongo-pvc
