version: '3'
services:
#  Kong Configuration
  kong-database:
    container_name: kong-database
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    networks:
      - kong-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  kong-migration:
    image: kong:latest
    command: "kong migrations bootstrap"
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_PG_HOST: kong-database
    links:
      - kong-database
    depends_on:
      - kong-database

  kong:
    container_name: kong
    restart: always
    networks:
      - kong-net
    image: kong
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    links:
      - kong-database
      - kong-migration
      - order-micro
    depends_on:
      - kong-database
      - kong-migration
      - order-micro
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_PROXY_LISTEN_SSL=0.0.0.0:8443
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15

##DBs
  mongodb-order:
    image: 'bitnami/mongodb'
    container_name: mongodb-order
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db/order
    networks:
      - kong-net
# Services

  order-micro:
    restart: always
    image: diegotony/orden-micro:travis
    ports:
      - "1396:1396"
    environment:
      - MONGO_URI=mongodb://mongodb-order:27017/order
      - PORT=1396
    depends_on:
      - mongodb-order
    links:
      - mongodb-order
    networks:
      kong-net:
        ipv4_address: 172.28.1.5

volumes:
  mongodb-data:

networks:
  kong-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
