version: '3'
services:
  mongo:
    image: 'mongo'
    ports:
      - "27011:27017"
    volumes:
      - data-dev-db:/data/db
    environment:
      - MONGODB_USERNAME=dev
      - MONGODB_PASSWORD=12345
      - MONGODB_DATABASE=bda
  # redis_db:
  #   image: 'redis:alpine'
  #   ports:
  #     - "6379:6379"
volumes:
  data-dev-db:
