apiVersion: v1
kind: Service
metadata:
  name: redis-publisher
spec:
  selector:
    app: redis-publisher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6379
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-publisher
  template:
    metadata:
      labels:
        app: redis-publisher
    spec:
      containers:
        - name: redis-publisher
          image: redis:alpine
          ports:
            - containerPort: 6379
          imagePullPolicy: Always
