_format_version: "1.1"

services:

- name: api-billing
  url: http://178.128.128.72/
  routes:
  - name: api-billing
    paths:
    - /api-billing

- name: api-client
  url:  http://178.128.128.11/
  routes:
  - name: api-client
    paths:
    - /api-client

- name: api-fee
  url: http://178.128.130.219/
  routes:
  - name: api-fee
    paths:
    - /api-fee

- name: api-order
  url:  http://68.183.248.154/
  routes:
  - name: api-order
    paths:
    - /api-order



