_format_version: "1.1"

services:

- name: api-billing
  url: http://165.227.242.93
  routes:
  - name: api-billing
    paths:
    - /api-billing

- name: api-client
  url:  http://167.99.27.14  
  routes:
  - name: api-client
    paths:
    - /api-client

- name: api-fee
  url: http://159.89.221.159 
  routes:
  - name: api-fee
    paths:
    - /api-fee

- name: api-order
  url:  http://159.89.220.83  
  routes:
  - name: api-order
    paths:
    - /api-order



