version: '3'
services:
  mongo:
    image: 'mongo'
    container_name: 'mongo'
    ports:
      - "27017:27017"
    volumes:
      - data-db:/data/db
  redis:
    container_name: 'redis'
    image: 'redis:alpine'
    ports:
      - "6379:6379"
volumes:
  data-db:
