apiVersion: v1
kind: Service
metadata:
  name: orden-api
spec:
  type: LoadBalancer
  selector:
    app: orden-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3037
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orden-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orden-api
  template:
    metadata:
      labels:
        app: orden-api
    spec:
      containers:
        - name: orden-micro
          image: diegotony/orden-micro:k8s
          ports:
            - containerPort: 3037
          env:
            - name: MONGO_HOST
              value: orden-mongo
            - name: REDIS_HOST
              value: redis-publisher
            # - name: PORT
            #   value: 3037
          imagePullPolicy: Always
---

