apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orden-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # storageClassName: do-block-storage
---
apiVersion: v1
kind: Pod
metadata:
  name: pods
  labels:
    app: myapp
spec:
  containers:
  - name: redis-publisher
    image: redis:alpine
    ports:
    - containerPort: 6379
    imagePullPolicy: Always

  - name: orden-mongo
    image: mongo:4.0.14-xenial
    ports:
      - containerPort: 27017
    volumeMounts:
      - name: orden-storage
        mountPath: /data/db
    imagePullPolicy: Always

  volumes:
  - name: orden-storage
    persistentVolumeClaim:
      claimName: orden-mongo-pvc
---
