apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-client
  name: mongodb-client
spec:
  ports:
  - name: "27019"
    port: 27019
    targetPort: 27017
  selector:
    io.kompose.service: mongodb-client
status:
  loadBalancer: {}
