apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: client-micro
  name: client-micro
spec:
  ports:
  - name: "4003"
    port: 4003
    targetPort: 4003
  selector:
    io.kompose.service: client-micro
status:
  loadBalancer: {}
