apiVersion:  apps/v1
kind: Deployment
metadata:
  name: client-micro
  labels:
    app: client-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-micro
  template:
    metadata:
      labels:
        app: client-micro
    spec:
      containers:
      - env:
        - name: MONGO_URI
          value: mongodb://mongodb-client:27017/client
        - name: PORT
          value: "4003"
        image: diegotony/client-micro:travis
        name: client-micro
        ports:
        - containerPort: 4003
        resources: {}
      restartPolicy: Always
status: {}
