apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: delivery-micro
  name: delivery-micro
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: delivery-micro
    spec:
      containers:
      - env:
        - name: MONGO_URI
          value: mongodb://mongodb-delivery:27017/delivery
        - name: PORT
          value: "4007"
        image: diegotony/delivery-micro:travis
        name: delivery-micro
        ports:
        - containerPort: 4007
        resources: {}
      restartPolicy: Always
status: {}
