apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kong-migration
  name: kong-migration
spec:
  containers:
  - args:
    - kong
    - migrations
    - bootstrap
    env:
    - name: KONG_PG_HOST
      value: kong-database
    image: kong:latest
    name: kong-migration
    resources: {}
  restartPolicy: OnFailure
status: {}
