apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fee-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # storageClassName: do-block-storage
  
---
apiVersion: v1
kind: Service
metadata:
  name: fee-mongo
spec:
  selector:
    app: fee-mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fee-mongo
spec:
  selector:
    matchLabels:
      app: fee-mongo
  template:
    metadata:
      labels:
        app: fee-mongo
    spec:
      containers:
        - name: fee-mongo
          image: mongo:4.0.14-xenial
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: fee-storage
              mountPath: /data/db
      volumes:
        - name: fee-storage
          persistentVolumeClaim:
            claimName: fee-mongo-pvc
