apiVersion: v1
kind: Service
metadata:
  name: fee-api
spec:
  selector: 
    app: fee-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3019
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fee-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fee-api 
  template:
    metadata:
      labels:
        app: fee-api
    spec:
      containers:
      - name: fee-micro
        image: diegotony/fee-micro:k8s
        ports:
          - containerPort: 3019
        env:
          - name: MONGO_HOST
            value: fee-mongo
          - name: REDIS_HOST
            value: redis-publisher
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        imagePullPolicy: Always
---


