apiVersion: v1
kind: Service
metadata:
  name: billing-api
spec:
  selector: 
    app: billing-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-api 
  template:
    metadata:
      labels:
        app: billing-api
    spec:
      containers:
      - name: billing-micro
        image: diegotony/billing-micro:k8s
        ports:
          - containerPort: 3001
        env:
          - name: MONGO_HOST
            value: billing-mongo
          - name: REDIS_HOST
            value: redis-publisher
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        imagePullPolicy: Always
---


