ports:
  develop:
    billing: 3001
    client: 3011
    delivery: 3019
    order: 3037
    payment: 3041
    frontend: 3049
    alt: 3061
  stagging:
    billing: 4001
    client: 4003
    delivery: 4007
    order: 4013
    payment: 4019
    frontend: 4021
    alt: 4027
  production:
    billing: 5003
    client: 5009
    delivery: 5011
    order: 5021
    payment: 5023
    frontend: 5039
    alt: 5051


ips:
  develop:
    billing: "localhost"
    client: "localhost"
    delivery: "localhost"
    order: "localhost"
    payment: "localhost"
    frontend: "localhost"
  stagging:
    billing: 172.28.1.1
    client: 172.28.1.2
    delivery: 172.28.1.3
    order: 172.28.1.4
    payment: 172.28.1.5
    frontend: 172.28.1.6
  production:
    billing: 172.28.1.1
    client: 172.28.1.2
    delivery: 172.28.1.3
    order: 172.28.1.4
    payment: 172.28.1.5
    frontend: 172.28.1.6

db:
  develop:
    billing: 27017
    client: 27017
    delivery: 27017
    order: 27017
    payment: 27017
    frontend: 27017
    alt: 27017
  stagging:
    billing: 27018
    client: 27019
    delivery: 27020
    order: 27021
    payment: 27022
  # production:
  #   billing: 5003
  #   client: 5009
  #   delivery: 5011
  #   order: 5021
  #   payment: 5023
  #   frontend: 5039
  #   alt: 5051