apiVersion: v1
kind: Service
metadata:
  name: delivery-api
spec:
  selector: 
    app: delivery-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3019
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-api 
  template:
    metadata:
      labels:
        app: delivery-api
    spec:
      containers:
      - name: delivery-micro
        image: diegotony/delivery-micro:k8s
        ports:
          - containerPort: 3019
        env:
          - name: MONGO_HOST
            value: delivery-mongo
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        imagePullPolicy: Always
---


