apiVersion: v1
kind: Service
metadata:
  name: billing-api
  labels:
    app: billing-api
spec:
  type: LoadBalancer
  selector: 
    app: billing-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-api
  labels:
    app: billing-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-api 
  template:
    metadata:
      labels:
        app: billing-api
    spec:
      containers:
      - name: billing-micro
        image: diegotony/billing-micro:k8s
        ports:
          - containerPort: 3001
        env:
          - name: MONGO_HOST
            value: billing-mongo
          - name: REDIS_HOST
            value: redis-publisher

        imagePullPolicy: Always
---


