_format_version: "1.1"

services:


- name: api-billing
  url: http://35.247.218.115
  routes:
  - name: api-billing
    paths:
    - /api-billing

- name: api-client
  url:  http://34.95.213.242
  routes:
  - name: api-client
    paths:
    - /api-client

- name: api-fee
  url: http://35.198.59.0
  routes:
  - name: api-fee
    paths:
    - /api-fee

- name: api-order
  url:  http://34.95.155.111
  routes:
  - name: api-order
    paths:
    - /api-order



