---
execution:
- concurrency: 100
  hold-for: 3m
  iterations: 100
  ramp-up: 30s
  scenario: quick-test
reporting:
- module: console
- dump-csv: perf_result_csv.csv
  failed-labels: false
  module: final-stats
  percentiles: true
  summary: true
  test-duration: true
- module: blazemeter
  project: Taurus test project
  report-name: Taurus test report
  test: Taurus test
  token: '********'
scenarios:
  quick-test:
    requests:
    - http://35.198.59.0/orden
    - http://35.198.59.0/billing
    - http://35.198.59.0/client
    - http://35.198.59.0/fee

