_format_version: "1.1"

services:


- name: api-billing
  url: http://35.199.100.227
  routes:
  - name: api-billing
    paths:
    - /api-billing

- name: api-client
  url:  http://34.95.136.252
  routes:
  - name: api-client
    paths:
    - /api-client

- name: api-fee
  url: http://34.95.153.71
  routes:
  - name: api-fee
    paths:
    - /api-fee

- name: api-order
  url:  http://34.95.167.124 
  routes:
  - name: api-order
    paths:
    - /api-order

plugins:
- name: cors
  service: api billing

  config: 
    methods:
    - GET
    - POST
    headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-MD5
    - Content-Type
    - Date
    - X-Auth-Token
    max_age: 3600